name: Build the image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
    - uses: actions/checkout@v3
    - name: Install podman
      run: sudo dnf install podman -y
    - name: Build the image
      run: podman build . --file Containerfile --tag asciidoctor:$(date +%s)
