name: Build the image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the image
      run: docker build . --file Containerfile --tag asciidoctor:$(date +%s)
